### ISSUE TITLE
Picking the best epoch

### ISSUE THREAD

**Issue by georgepar** [martinmamql/Interpretable-Multimodal-Routing-for-Human-Multimodal-Language#2] opened 2021-03-17 11:45 UTC
Hi, 

I am trying to reproduce the paper results and I noticed that you use the test accuracy to pick the best epoch [here](https://github.com/martinmamql/multimodal_routing/blob/master/main.py#L289)

```
is_best = test_acc > best_acc
```

This is probably a bug, as it should be

```
is_best = val_acc > best_acc
```

**Comment by martinmamql** [comment] 2021-03-18 18:20
Hi Giorgos. 

Greetings! Thank you very much for your reply! 

If possible, would you mind waiting a bit (a week or two) before I submit a finalized version of the code base? I sincerely apologize for this, and I will upload a clean, finalized version as soon as I could.

Thank you very much for your patience and understanding!

Sincerely,
Martin

**Comment by srb-cv** [comment] 2022-09-22 09:29
Hi Martin Q. Ma,
Is there any update on this issue? I still see that while reproducing the results, the checkpoints are being saved on the basis of best test accuracy rather than validation accuracy.

**Comment by martinmamql** [comment] 2022-10-23 16:43
Sorry for the long, long wait -- the issue is fixed now. Thank you very much for your very patience and understanding!

**Closed as completed** 2022-10-23 16:43 UTC
